# This is core setting for entire project
# You can import these info anywhere in the pj

import os
from dotenv import load_dotenv

load_dotenv()

# Notion Related
import os

GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

NARRATIVE_TELEGRAM_BOT_TOKEN = os.getenv("NARRATIVE_TELEGRAM_BOT_TOKEN")
NARRATIVE_TELEGRAM_SECRET_TOKEN = os.getenv("NARRATIVE_TELEGRAM_SECRET_TOKEN")
IMPACT_TELEGRAM_BOT_TOKEN = os.getenv("IMPACT_TELEGRAM_BOT_TOKEN")
IMPACT_TELEGRAM_SECRET_TOKEN = os.getenv("IMPACT_TELEGRAM_SECRET_TOKEN")
CHATBOT_TELEGRAM_BOT_TOKEN = os.getenv('CHATBOT_TELEGRAM_BOT_TOKEN')
CHATBOT_TELEGRAM_SECRET_TOKEN = os.getenv('CHATBOT_TELEGRAM_SECRET_TOKEN')
PORTFOLIO_TELEGRAM_BOT_TOKEN = os.getenv('PORTFOLIO_TELEGRAM_BOT_TOKEN')
PORTFOLIO_TELEGRAM_SECRET_TOKEN = os.getenv('PORTFOLIO_TELEGRAM_SECRET_TOKEN')


# ------<Notion API KEY>-------
# Connect to Workspace
NOTION_API_KEY = os.getenv("NOTION_API_KEY")
NOTION_CHAT_API_KEY = os.getenv("NOTION_CHAT_API_KEY")
NOTION_PORTFOLIO_API_KEY=os.getenv("NOTION_PORTFOLIO_API_KEY")


# ------<Notion DB Narrative/Impact-db>-------
NOTION_ROOT_PAGE_ID = os.getenv("NOTION_ROOT_PAGE_ID")
NOTION_DATABASE_ID = os.getenv("NOTION_DATABASE_ID")

NOTION_SCHOOLS_DB_ID = os.getenv("NOTION_SCHOOLS_DB_ID")
NOTION_TEACHERS_DB_ID = os.getenv("NOTION_TEACHERS_DB_ID")
NOTION_NARRATIVES_DB_ID = os.getenv("NOTION_NARRATIVES_DB_ID")

NOTION_SUBJECTS_DB_ID= os.getenv("NOTION_SUBJECTS_DB_ID")
NOTION_STAFF_NARRATIVES_DB_ID= os.getenv("NOTION_STAFF_NARRATIVES_DB_ID")

# ------<Notion DBPortfolio>-------
NOTION_TEACHER_PORTFOLIO_DB=os.getenv("NOTION_TEACHER_PORTFOLIO_DB")
NOTION_PORTFOLIO_USER_DB=os.getenv("NOTION_PORTFOLIO_USER_DB")


OPENAI_EMBED_MODEL = os.getenv("OPENAI_EMBED_MODEL")
OPENAI_LLM_MODEL = os.getenv("OPENAI_LLM_MODEL")
CATEGORY_MODE = os.getenv("CATEGORY_MODE")
CHROMA_DIR = os.getenv("CHROMA_DIR")
CATEGORY_SEED_PATH = os.getenv("CATEGORY_SEED_PATH")

# The duration of the time-window: Test=15min / Development=18hours
NARRATIVE_WINDOW_MINUTES = int(os.getenv("NARRATIVE_WINDOW_MINUTES", "15"))

# if not all([IMPACT_TELEGRAM_BOT_TOKEN, IMPACT_TELEGRAM_SECRET_TOKEN]):
#     raise RuntimeError('Missing required env vars. Check .env')